name: ExampleiOSApp
options:
  minimumXcodeGenVersion: 2.37.0
packages:
  onnxruntime:
    url: https://github.com/microsoft/onnxruntime-swift-package-manager.git
    from: 1.16.0
targets:
  ExampleiOSApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: .
      - path: ../../swift/Sources/Helper.swift <<- 여기
        type: file
    resources:
      - path: onnx
        type: folder
      - path: audio
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.supertonic.ExampleiOSApp
        SWIFT_VERSION: 5.9
        INFOPLIST_FILE: Info.plist
    dependencies:
      - package: onnxruntime
        product: onnxruntime
